name: 'gitdoc-sync-docker'
description: 'Build Git doc to other platform'
inputs:
  yuqueNamespace:
    required: true
  yuqueSite:
    required: true
  yuqueToken:
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.yuqueNamespace }}
    - ${{ inputs.yuqueSite }}
    - ${{ inputs.yuqueToken }}

      
